name: Build and Deploy Site

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  modify-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Run Blog generator
        run: node js/build.js

      - name: Check for changes
        id: check-changes
        run: |
          if git diff --quiet && git diff --staged --quiet; then
            echo "changes=false" >> $GITHUB_OUTPUT
          else
            echo "changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push
        if: steps.check-changes.outputs.changes == 'true'
        run: |
          git add posts/rss_feed.xml posts/articles/
          git commit -m "Automated update: $(date +'%Y-%m-%d %H:%M:%S')"
          git push
